query GetAllCars {
  allCars {
    totalCount
    nodes {
      id
      name
      images
      year
    }
  }
}

query GetCar($id: Int!) {
  carById(id: $id) {
    id
    images
    name
    year
  }
}
